import Link from "next/link";
import { RefractiveLens } from "@/components/specimens/refractive-lens/RefractiveLens";

export const metadata = {
  title: "Refractive lens — a design note",
  description:
    "A draggable glass loupe over an editorial page. Real refraction, generated by the cursor — magnification, edge compression, and a thin spectrum at the rim — with the paper left calm.",
  robots: { index: false, follow: false },
};

const NOTES: { term: string; detail: string }[] = [
  {
    term: "Refraction, not a filter",
    detail:
      "The lens samples the page through a plano-convex displacement model: magnified at the centre, relaxing continuously to 1:1 at the rim so the edge never tears the type. The bending is the optics, not a blur slapped on top.",
  },
  {
    term: "Spectrum only where it earns it",
    detail:
      "Chromatic aberration appears solely in the outer rim band, scaled by how hard the glass is bending there — the way a real lens fringes at its edge and stays clean through the middle. No colour is added to the page itself.",
  },
  {
    term: "Glass with weight",
    detail:
      "The lens chases the pointer through a critically-damped spring, so it lags and settles instead of snapping. A contact shadow and a single specular arc seat it on the paper without a drop of gradient.",
  },
  {
    term: "The paper stays calm",
    detail:
      "The page is set in the site's own type on warm stock, black ink, one Klein-blue mark. All the spectacle is in the seeing, not the surface — restraint is the whole argument.",
  },
];

export default function Page() {
  return (
    <main
      style={{
        minHeight: "100vh",
        padding: "var(--space-9) 64px var(--space-9)",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        gap: "var(--space-8)",
      }}
    >
      <header style={{ width: "100%", maxWidth: 760 }}>
        <Link
          href="/"
          style={{
            fontFamily: "var(--font-geist-mono)",
            fontSize: 12,
            letterSpacing: "0.14em",
            textTransform: "uppercase",
            color: "var(--color-gray-11)",
            textDecoration: "none",
          }}
        >
          ← Back home
        </Link>
        <p
          style={{
            marginTop: "var(--space-6)",
            fontFamily: "var(--font-geist-mono)",
            fontSize: 12,
            letterSpacing: "0.14em",
            textTransform: "uppercase",
            color: "var(--color-gray-11)",
          }}
        >
          Design note · Refractive lens
        </p>
        <h1
          style={{
            margin: "var(--space-3) 0 0",
            fontSize: "clamp(36px, 5vw, 60px)",
            lineHeight: 1.04,
            letterSpacing: "-0.02em",
            color: "var(--color-gray-12)",
          }}
        >
          A page you read with your hands
        </h1>
        <p
          style={{
            margin: "var(--space-5) 0 0",
            maxWidth: 620,
            fontSize: "var(--fs-18, 18px)",
            lineHeight: 1.5,
            color: "var(--color-gray-11)",
          }}
        >
          A single colourless lens, dragged across an editorial column. It does
          only what real glass does — gather the type and bend it — magnifying
          the centre, compressing the rim, and splitting a thin spectrum at the
          edge. Move the cursor over the page and look closer.
        </p>
      </header>

      <div
        style={{
          alignSelf: "center",
          width: "100%",
          maxWidth: 880,
          aspectRatio: "4 / 5",
          borderRadius: 16,
          overflow: "hidden",
          border: "1px solid var(--color-hairline)",
          boxShadow: "0 24px 60px -28px rgba(0,0,0,0.28)",
        }}
      >
        <RefractiveLens />
      </div>

      <section style={{ width: "100%", maxWidth: 760 }}>
        <p
          style={{
            fontFamily: "var(--font-geist-mono)",
            fontSize: 12,
            letterSpacing: "0.14em",
            textTransform: "uppercase",
            color: "var(--color-gray-11)",
          }}
        >
          What I decided, and why
        </p>

        <dl
          style={{
            margin: "var(--space-6) 0 0",
            display: "flex",
            flexDirection: "column",
            gap: "var(--space-7)",
          }}
        >
          {NOTES.map((note) => (
            <div key={note.term}>
              <dt
                style={{
                  fontSize: "var(--fs-20, 20px)",
                  letterSpacing: "-0.01em",
                  color: "var(--color-gray-12)",
                }}
              >
                {note.term}
              </dt>
              <dd
                style={{
                  margin: "var(--space-3) 0 0",
                  maxWidth: 620,
                  fontSize: "var(--fs-18, 18px)",
                  lineHeight: 1.5,
                  color: "var(--color-gray-11)",
                }}
              >
                {note.detail}
              </dd>
            </div>
          ))}
        </dl>
      </section>
    </main>
  );
}
