"use client";

import { useEffect, useRef } from "react";

/*
 * RefractiveLens — a draggable optical loupe over editorial typography.
 *
 * The visual-first interaction specimen in register A (restrained but
 * visually rich): a calm paper page set in the site's own type, with a
 * single colourless glass lens that bends, magnifies, and chromatically
 * fringes the text beneath it. No glow, no gradient — the only spectacle
 * is real refraction, generated by the cursor.
 *
 * Pipeline:
 *   1. Lay out a short editorial column onto an offscreen 2D canvas at
 *      device-pixel resolution (the "page"). Drawn once, re-drawn on
 *      resize.
 *   2. Upload that canvas as a GL texture.
 *   3. Render one full-stage quad whose fragment shader, inside the lens
 *      radius, samples the page through a plano-convex displacement model:
 *      magnified at the centre, falling continuously to 1:1 at the rim
 *      (so the lens edge never tears the text), with the outer rim band
 *      compressing the type and splitting it into faint RGB fringes. A
 *      soft specular arc and a contact shadow seat the glass on the paper.
 *
 * Motion: the lens follows the pointer through a critically-damped spring
 * so it carries weight; with no pointer it drifts on a slow Lissajous.
 * prefers-reduced-motion disables idle drift and the intro reveal but
 * leaves direct pointer control intact.
 */

/* ─── Editorial page content (the material the lens reads) ───────────── */

type Block =
  | { kind: "eyebrow"; text: string }
  | { kind: "title"; text: string }
  | { kind: "lede"; text: string; dropCap: true }
  | { kind: "body"; text: string }
  | { kind: "rule" }
  | { kind: "folio"; text: string };

const PAGE_BLOCKS: Block[] = [
  { kind: "eyebrow", text: "SPECIMEN · OPTICS" },
  { kind: "title", text: "Reading is an act of focus" },
  {
    kind: "lede",
    dropCap: true,
    text:
      "A lens does only one honest thing: it gathers what is already there and asks you to look harder. It adds no colour the page did not have, invents no detail the ink did not carry. The drama at its edge — the bending, the thin seam of spectrum — is not decoration. It is the cost of magnification made visible.",
  },
  {
    kind: "body",
    text:
      "An interface can work the same way. Most products prove themselves with packaging: a wash of gradient, a sheet of glass, light blooming off nothing. It buys a feeling — new, technical — and tells you nothing about the work underneath.",
  },
  {
    kind: "body",
    text:
      "The restraint is the argument. If the type is set well, if the column is measured and the rhythm is true, then the only thing left to add is a way of seeing it more closely. The lens is that way. Move it, and the page answers.",
  },
  { kind: "rule" },
  { kind: "folio", text: "RYANZHANG.WORK · REFRACTIVE LENS · 01" },
];

/* ─── Palette (paper register — no pure black/white) ─────────────────── */

const PAPER = "#f4f3ee"; // warm off-white ground
const INK = "#1b1b19"; // near-black body ink
const INK_SOFT = "#6b6a64"; // muted (eyebrow / folio)
const ACCENT = "#002fa7"; // Klein blue — single brand accent

/* ─── Shaders ────────────────────────────────────────────────────────── */

const VERT = `
attribute vec2 a_pos;
varying vec2 v_uv;
void main() {
  v_uv = a_pos * 0.5 + 0.5;
  gl_Position = vec4(a_pos, 0.0, 1.0);
}
`;

// All distances in device pixels. The page texture maps 1:1 to the stage,
// so pixel→uv is just /resolution (with a y-flip, since canvas 2D is
// top-left origin and GL textures are bottom-left).
const FRAG = `
precision highp float;

varying vec2 v_uv;

uniform sampler2D u_tex;
uniform vec2  u_res;      // stage size in device px
uniform vec2  u_center;   // lens centre in device px (top-left origin)
uniform float u_radius;   // lens radius in device px
uniform float u_mag;      // centre magnification

vec4 samplePage(vec2 px) {
  // Texture uploaded with UNPACK_FLIP_Y = false, so row 0 of the canvas
  // (its top) is texel v = 0. px is top-left origin, so v = px.y / H maps
  // screen-top to canvas-top with no vertical flip.
  vec2 uv = vec2(px.x / u_res.x, px.y / u_res.y);
  return texture2D(u_tex, uv);
}

void main() {
  // Fragment position in top-left device px.
  vec2 fragPx = vec2(v_uv.x * u_res.x, (1.0 - v_uv.y) * u_res.y);
  vec2 toFrag = fragPx - u_center;
  float d = length(toFrag);
  float R = u_radius;

  // Antialiased lens mask.
  float aa = 1.25;
  float inside = 1.0 - smoothstep(R - aa, R + aa, d);

  vec4 flatCol = samplePage(fragPx);

  if (inside <= 0.0) {
    // Outside the glass: flat page + a soft contact shadow ring, offset
    // slightly down-right so the glass reads as sitting above the paper.
    vec2 shadowFrom = fragPx - u_center - vec2(R * 0.06, R * 0.05);
    float sd = length(shadowFrom);
    float shadow = smoothstep(R * 1.16, R * 0.99, sd)
                 * (1.0 - smoothstep(R * 0.99, R * 0.92, sd));
    gl_FragColor = vec4(flatCol.rgb * (1.0 - shadow * 0.18), 1.0);
    return;
  }

  vec2 dir = toFrag / max(d, 1e-4);
  float r = d / R;                     // 0 centre → 1 rim

  // Plano-convex displacement. z is the height of a spherical cap (1 at
  // centre, 0 at rim). Pulling the sample toward the centre by (1 - 1/mag)
  // scaled by z magnifies the middle and relaxes to 1:1 at the rim, so the
  // refracted field is continuous with the flat page across the edge.
  float z = sqrt(max(1.0 - r * r, 0.0));
  float pull = (1.0 - 1.0 / u_mag) * z;
  vec2 srcPx = u_center + toFrag * (1.0 - pull);

  // Rim refraction: in the outer band, push the sample further out so the
  // type compresses against the glass edge.
  float rim = smoothstep(0.78, 1.0, r);
  srcPx += dir * rim * R * 0.10;

  // Chromatic aberration — only at the rim, scaled by how hard the glass
  // is bending there. R and B sample along the radial axis, G stays put.
  float ca = rim * R * 0.012;
  float cr = samplePage(srcPx + dir * ca).r;
  float cg = samplePage(srcPx).g;
  float cb = samplePage(srcPx - dir * ca).b;
  vec3 col = vec3(cr, cg, cb);

  // Inner bright rim — a thin highlight just inside the edge.
  float ring = smoothstep(0.93, 0.985, r) * (1.0 - smoothstep(0.985, 1.0, r));
  col += ring * 0.06;

  // Specular arc — a soft glare toward the top-left of the lens.
  vec2 hl = u_center + vec2(-0.34, -0.40) * R;
  float hd = length(fragPx - hl);
  float spec = smoothstep(R * 0.62, 0.0, hd) * 0.10;
  col += spec * inside;

  // Faint edge darkening to give the glass body some thickness.
  col *= 1.0 - rim * 0.05;

  gl_FragColor = vec4(mix(flatCol.rgb, col, inside), 1.0);
}
`;

/* ─── Component ──────────────────────────────────────────────────────── */

export function RefractiveLens({ className }: { className?: string }) {
  const wrapRef = useRef<HTMLDivElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const wrap = wrapRef.current;
    const canvas = canvasRef.current;
    if (!wrap || !canvas) return;

    const gl =
      canvas.getContext("webgl", {
        antialias: true,
        premultipliedAlpha: false,
        // Persist the buffer so a redraw on tab-refocus (rAF is paused while
        // hidden) shows immediately instead of a cleared frame.
        preserveDrawingBuffer: true,
      }) || canvas.getContext("experimental-webgl");
    if (!gl || !(gl instanceof WebGLRenderingContext)) {
      // No WebGL — leave the static <noscript>-style fallback drawn below.
      drawFallback(canvas, wrap);
      return;
    }

    const reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches;

    /* — program — */
    const prog = buildProgram(gl, VERT, FRAG);
    if (!prog) return;
    gl.useProgram(prog);

    const posLoc = gl.getAttribLocation(prog, "a_pos");
    const buf = gl.createBuffer();
    gl.bindBuffer(gl.ARRAY_BUFFER, buf);
    // Full-stage quad (two triangles).
    gl.bufferData(
      gl.ARRAY_BUFFER,
      new Float32Array([-1, -1, 1, -1, -1, 1, -1, 1, 1, -1, 1, 1]),
      gl.STATIC_DRAW,
    );
    gl.enableVertexAttribArray(posLoc);
    gl.vertexAttribPointer(posLoc, 2, gl.FLOAT, false, 0, 0);

    const uTex = gl.getUniformLocation(prog, "u_tex");
    const uRes = gl.getUniformLocation(prog, "u_res");
    const uCenter = gl.getUniformLocation(prog, "u_center");
    const uRadius = gl.getUniformLocation(prog, "u_radius");
    const uMag = gl.getUniformLocation(prog, "u_mag");

    const tex = gl.createTexture();
    gl.bindTexture(gl.TEXTURE_2D, tex);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR);
    gl.uniform1i(uTex, 0);
    gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, false);

    /* — sizing / page texture — */
    let dpr = 1;
    let cssW = 0;
    let cssH = 0;
    let radius = 120;
    const MAG = 1.85;

    const fontFamily = resolveFontFamily(wrap);

    let ready = false;

    // Returns false if the wrapper has no usable size yet (e.g. an
    // aspect-ratio box before layout settles) — drawing a 2px texture would
    // throw the typography away, so we bail and retry rather than commit junk.
    const rebuild = () => {
      const rect = wrap.getBoundingClientRect();
      if (rect.width < 40 || rect.height < 40) {
        ready = false;
        return false;
      }
      cssW = rect.width;
      cssH = rect.height;
      dpr = Math.min(window.devicePixelRatio || 1, 2);

      canvas.width = Math.round(cssW * dpr);
      canvas.height = Math.round(cssH * dpr);
      canvas.style.width = `${cssW}px`;
      canvas.style.height = `${cssH}px`;

      radius = Math.max(74, Math.min(cssW, cssH) * 0.2) * dpr;

      const page = renderPage(cssW * dpr, cssH * dpr, dpr, fontFamily);
      gl.bindTexture(gl.TEXTURE_2D, tex);
      gl.texImage2D(
        gl.TEXTURE_2D,
        0,
        gl.RGBA,
        gl.RGBA,
        gl.UNSIGNED_BYTE,
        page,
      );
      gl.viewport(0, 0, canvas.width, canvas.height);
      ready = true;
      return true;
    };

    /* — motion state (device px, top-left origin) — */
    const state = {
      tx: 0,
      ty: 0, // spring target
      cx: 0,
      cy: 0, // current centre
      vx: 0,
      vy: 0,
      hasPointer: false,
      introT: 1,
      t0: 0,
    };

    const seedCentre = () => {
      state.tx = canvas.width * 0.5;
      state.ty = canvas.height * 0.46;
      state.cx = state.tx;
      state.cy = state.ty;
    };

    // Draw the current frame. Pulled out of the rAF loop so we can paint
    // synchronously the moment we're sized — rAF is throttled to zero while
    // the page is backgrounded, so the first frame must not depend on it.
    const paint = () => {
      if (!ready) return;
      const eased = 1 - Math.pow(1 - state.introT, 3);
      gl.uniform2f(uRes, canvas.width, canvas.height);
      gl.uniform2f(uCenter, state.cx, state.cy);
      gl.uniform1f(uRadius, radius * eased);
      gl.uniform1f(uMag, MAG);
      gl.drawArrays(gl.TRIANGLES, 0, 6);
    };

    const onResize = () => {
      const wasReady = ready;
      rebuild();
      if (ready && !wasReady) seedCentre();
      paint();
    };

    // Try until the aspect-ratio box reports a real size, then seed the lens.
    let sizeAttempts = 0;
    const trySize = () => {
      if (rebuild()) {
        seedCentre();
        paint();
        return;
      }
      if (sizeAttempts++ < 60) requestAnimationFrame(trySize);
    };
    trySize();

    // The page texture is laid out with ctx.measureText — which needs the
    // webfont loaded, or every block collapses on bad metrics. The first
    // rebuild() above runs synchronously (fonts may still be pending); redraw
    // the texture once they resolve so the column lays out correctly.
    let cancelled = false;
    if (document.fonts?.status !== "loaded") {
      document.fonts.ready.then(() => {
        if (cancelled) return;
        rebuild();
        paint();
      });
    }

    /* — pointer — */
    const toDevice = (clientX: number, clientY: number) => {
      const rect = canvas.getBoundingClientRect();
      return [
        (clientX - rect.left) * dpr,
        (clientY - rect.top) * dpr,
      ] as const;
    };
    const onPointerMove = (e: PointerEvent) => {
      const [x, y] = toDevice(e.clientX, e.clientY);
      state.tx = x;
      state.ty = y;
      state.hasPointer = true;
    };
    const onPointerLeave = () => {
      state.hasPointer = false;
    };
    canvas.addEventListener("pointermove", onPointerMove);
    canvas.addEventListener("pointerleave", onPointerLeave);

    const ro = new ResizeObserver(onResize);
    ro.observe(wrap);

    /* — loop — */
    let raf = 0;
    let last = 0;
    const tick = (now: number) => {
      if (!last) last = now;
      const dt = Math.min((now - last) / 1000, 0.05);
      last = now;
      if (!state.t0) state.t0 = now;

      // Wait for a real size before drawing — never commit a 2px frame.
      if (!ready) {
        raf = requestAnimationFrame(tick);
        return;
      }

      // Idle drift on a slow Lissajous when the pointer is away.
      if (!state.hasPointer && !reduced) {
        const t = (now - state.t0) / 1000;
        const mx = canvas.width * 0.5;
        const my = canvas.height * 0.46;
        const ax = canvas.width * 0.26;
        const ay = canvas.height * 0.2;
        state.tx = mx + Math.sin(t * 0.34) * ax;
        state.ty = my + Math.sin(t * 0.27 + 1.1) * ay;
      }

      // Critically-damped spring toward target → weight + lag.
      const k = 120; // stiffness
      const dmp = 2 * Math.sqrt(k) * 0.9;
      const ax = (state.tx - state.cx) * k - state.vx * dmp;
      const ay = (state.ty - state.cy) * k - state.vy * dmp;
      state.vx += ax * dt;
      state.vy += ay * dt;
      state.cx += state.vx * dt;
      state.cy += state.vy * dt;

      paint();

      raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);

    return () => {
      cancelled = true;
      cancelAnimationFrame(raf);
      ro.disconnect();
      canvas.removeEventListener("pointermove", onPointerMove);
      canvas.removeEventListener("pointerleave", onPointerLeave);
      gl.deleteProgram(prog);
      gl.deleteBuffer(buf);
      gl.deleteTexture(tex);
    };
  }, []);

  return (
    <div
      ref={wrapRef}
      className={className}
      style={{
        position: "relative",
        width: "100%",
        height: "100%",
        background: PAPER,
        borderRadius: 12,
        overflow: "hidden",
        cursor: "crosshair",
        touchAction: "none",
      }}
    >
      <canvas
        ref={canvasRef}
        style={{ display: "block", width: "100%", height: "100%" }}
        aria-label="An editorial page read through a draggable glass lens"
        role="img"
      />
    </div>
  );
}

/* ─── GL helpers ─────────────────────────────────────────────────────── */

function buildProgram(gl: WebGLRenderingContext, vsrc: string, fsrc: string) {
  const compile = (type: number, src: string) => {
    const sh = gl.createShader(type);
    if (!sh) return null;
    gl.shaderSource(sh, src);
    gl.compileShader(sh);
    if (!gl.getShaderParameter(sh, gl.COMPILE_STATUS)) {
      console.error("[RefractiveLens] shader:", gl.getShaderInfoLog(sh));
      gl.deleteShader(sh);
      return null;
    }
    return sh;
  };
  const vs = compile(gl.VERTEX_SHADER, vsrc);
  const fs = compile(gl.FRAGMENT_SHADER, fsrc);
  if (!vs || !fs) return null;
  const prog = gl.createProgram();
  if (!prog) return null;
  gl.attachShader(prog, vs);
  gl.attachShader(prog, fs);
  gl.linkProgram(prog);
  gl.deleteShader(vs);
  gl.deleteShader(fs);
  if (!gl.getProgramParameter(prog, gl.LINK_STATUS)) {
    console.error("[RefractiveLens] link:", gl.getProgramInfoLog(prog));
    return null;
  }
  return prog;
}

/* ─── Page rendering (the texture the lens reads) ────────────────────── */

/* Resolve the hashed next/font family name by reading the computed style
 * of a probe styled with the --font-inter variable. Falls back to a system
 * stack if the var is unset (e.g. SSR mismatch). */
function resolveFontFamily(host: HTMLElement): string {
  const probe = document.createElement("span");
  probe.style.fontFamily = "var(--font-inter)";
  host.appendChild(probe);
  const fam = getComputedStyle(probe).fontFamily;
  host.removeChild(probe);
  return fam && fam !== "var(--font-inter)"
    ? fam
    : "Inter, system-ui, sans-serif";
}

/* Lay the editorial column out onto an offscreen canvas at device px. */
function renderPage(
  w: number,
  h: number,
  dpr: number,
  fontFamily: string,
): HTMLCanvasElement {
  const c = document.createElement("canvas");
  c.width = Math.round(w);
  c.height = Math.round(h);
  const ctx = c.getContext("2d")!;
  ctx.scale(dpr, dpr);

  const W = w / dpr;
  const H = h / dpr;

  // Ground.
  ctx.fillStyle = PAPER;
  ctx.fillRect(0, 0, W, H);

  // Print margins — generous, book-like.
  const marginX = Math.max(40, W * 0.12);
  const colW = W - marginX * 2;
  let y = Math.max(48, H * 0.1);

  ctx.textBaseline = "alphabetic";

  const wrapText = (
    text: string,
    font: string,
    lineHeight: number,
    color: string,
    opts: { firstLineIndent?: number; indentLines?: number } = {},
  ) => {
    ctx.font = font;
    ctx.fillStyle = color;
    const words = text.split(/\s+/);
    let line = "";
    let lineIndex = 0;
    const indent = opts.firstLineIndent ?? 0;
    const indentLines = opts.indentLines ?? 0;
    const xFor = (idx: number) =>
      marginX + (idx < indentLines ? indent : 0);
    const widthFor = (idx: number) =>
      colW - (idx < indentLines ? indent : 0);

    for (let i = 0; i < words.length; i++) {
      const test = line ? `${line} ${words[i]}` : words[i];
      if (ctx.measureText(test).width > widthFor(lineIndex) && line) {
        ctx.fillText(line, xFor(lineIndex), y);
        y += lineHeight;
        lineIndex++;
        line = words[i];
      } else {
        line = test;
      }
    }
    if (line) {
      ctx.fillText(line, xFor(lineIndex), y);
      y += lineHeight;
    }
  };

  for (const block of PAGE_BLOCKS) {
    switch (block.kind) {
      case "eyebrow": {
        y += 4;
        ctx.font = `600 13px ${fontFamily}`;
        ctx.fillStyle = ACCENT;
        // Letter-spacing by hand.
        drawTracked(ctx, block.text, marginX, y, 2.4);
        y += 30;
        break;
      }
      case "title": {
        wrapText(block.text, `700 40px ${fontFamily}`, 46, INK);
        y += 18;
        break;
      }
      case "lede": {
        // Drop cap: big initial, first lines indent around it.
        const initial = block.text[0];
        const rest = block.text.slice(1);
        const capSize = 64;
        ctx.font = `700 ${capSize}px ${fontFamily}`;
        ctx.fillStyle = INK;
        const capW = ctx.measureText(initial).width;
        ctx.fillText(initial, marginX, y + capSize * 0.74);
        wrapText(rest, `400 19px ${fontFamily}`, 30, INK, {
          firstLineIndent: capW + 12,
          indentLines: 2,
        });
        y += 16;
        break;
      }
      case "body": {
        wrapText(block.text, `400 19px ${fontFamily}`, 30, INK);
        y += 14;
        break;
      }
      case "rule": {
        y += 8;
        ctx.strokeStyle = "rgba(0,0,0,0.16)";
        ctx.lineWidth = 1;
        ctx.beginPath();
        ctx.moveTo(marginX, y);
        ctx.lineTo(marginX + colW, y);
        ctx.stroke();
        y += 28;
        break;
      }
      case "folio": {
        ctx.font = `500 12px ${fontFamily}`;
        ctx.fillStyle = INK_SOFT;
        drawTracked(ctx, block.text, marginX, y, 1.6);
        y += 24;
        break;
      }
    }
  }

  return c;
}

/* Manual letter-spacing (canvas ctx.letterSpacing is not universally safe). */
function drawTracked(
  ctx: CanvasRenderingContext2D,
  text: string,
  x: number,
  y: number,
  tracking: number,
) {
  let cx = x;
  for (const ch of text) {
    ctx.fillText(ch, cx, y);
    cx += ctx.measureText(ch).width + tracking;
  }
}

/* Static fallback when WebGL is unavailable — just the flat page. */
function drawFallback(canvas: HTMLCanvasElement, wrap: HTMLElement) {
  const rect = wrap.getBoundingClientRect();
  const dpr = Math.min(window.devicePixelRatio || 1, 2);
  canvas.width = Math.round(rect.width * dpr);
  canvas.height = Math.round(rect.height * dpr);
  canvas.style.width = `${rect.width}px`;
  canvas.style.height = `${rect.height}px`;
  const page = renderPage(
    rect.width * dpr,
    rect.height * dpr,
    dpr,
    resolveFontFamily(wrap),
  );
  canvas.getContext("2d")?.drawImage(page, 0, 0);
}
